export const CHATS_RECEIVED = 'CHATS_RECEIVED';
export const MESSAGES_RECEIVED = 'MESSAGES_RECEIVED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const USER_UPDATED = 'USER_UPDATED';